#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Eduardo Sebastian <esebastian@altiora.es>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# set global settings
LOCAL=/usr/local
CASKROOM=/opt/Caskroom

# set up common environment variables
export HOMEBREW_CASK_OPTS="--caskroom=$CASKROOM"
export JAVA_HOME=/Library/Java/Home
export SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -Dsbt.ivy.home=$LOCAL/var/lib/ivy2/ -Divy.home=$LOCAL/var/lib/ivy2/"
export PG_ROOT=/Applications/Postgres.app/Contents/Versions/9.6
export PYENV_ROOT=$LOCAL/var/lib/pyenv
export RBENV_ROOT=$LOCAL/var/lib/rbenv
export NODENV_ROOT=$LOCAL/var/lib/nodenv

# set terminal colors
if [[ ! "$TERM_PROGRAM" = "Apple_Terminal" ]]; then
  export LSCOLORS='ExFxCxDxBxegedabagacad'
  export LS_COLORS='di=1;34:ln=1;35:so=1;32:pi=1;33:ex=1;31:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=34;43:'
fi
