#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Eduardo Sebastian <esebastian@altiora.es>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# set global settings
local_path="/usr/local" # $(brew --prefix)

# set up common environment variables
export JAVA_HOME=/Library/Java/Home
export GRADLE_OPTS=-Dgradle.user.home=${local_path}/var/cache/gradle
export SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -Dsbt.ivy.home=${local_path}/var/cache/ivy2/ -Divy.home=${local_path}/var/cache/ivy2/"
export PG_ROOT=/Applications/Postgres.app/Contents/Versions/9.6
export PYENV_ROOT=${local_path}/var/lib/pyenv
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export RBENV_ROOT=${local_path}/var/lib/rbenv
export NODENV_ROOT=${local_path}/var/lib/nodenv
export GOPATH=$HOME/Code/go
export MIX_HOME=${local_path}/var/cache/mix
export HEX_HOME=${local_path}/var/cache/hex

# set terminal colors
if [[ ! "$TERM_PROGRAM" = "Apple_Terminal" ]]; then
  export LSCOLORS='ExFxCxDxBxegedabagacad'
  export LS_COLORS='di=1;34:ln=1;35:so=1;32:pi=1;33:ex=1;31:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=34;43:'
fi
